(module rsc3 scheme/base
(require mzlib/include)
(require rsc3/mzscheme/structure)
(require rsc3/mzscheme/r6rs)
(require rsc3/mzscheme/udp)
(provide (all-defined-out))
(include "hscheme.scm")
(include "common.scm")
(include "sosc.scm")
(include "graphdef.scm")
(include "ugen.scm")
(include "server.scm")
(include "supercollider.scm")
(include "random.scm")
)
