(module rsc3 scheme/base
(require mzlib/include)
(require rsc3/mzscheme/structure)
(require (prefix-in r6rs: rnrs/bytevectors-6))
(require (prefix-in r6rs: rnrs/io/ports-6))
(require (prefix-in r6rs: rsc3/mzscheme/r6rs))
(require rsc3/mzscheme/udp)
(require hscheme/plt/hscheme)
(provide (all-defined-out))
(include "common.scm")
(include "sosc.scm")
(include "graphdef.scm")
(include "ugen.scm")
(include "server.scm")
(include "supercollider.scm")
)
