(module rsc3 scheme/base
(require mzlib/include)
(require rhs/plt/rhs)
(require sosc/plt/sosc)
(provide (all-defined-out))
(define div quotient)
;(define mod modulo)
(define random-real random)
(include "../src/rsc3.scm")
)
