;; fft.scm - (c) rohan drape, 2005

(define-specialized FFT (buf in) 1 kr)
(define-specialized IFFT (buf) 1 ar)
(define-specialized PV_Add (bufA bufB) 1 kr)
(define-specialized PV_BinScramble (buffer wipe width trig))
(define-specialized PV_BinShift ())
(define-specialized PV_BinWipe ())
(define-specialized PV_BrickWall ())
(define-specialized PV_ConformalMap ())
(define-specialized PV_CopyPhase ())
(define-specialized PV_Diffuser ())
(define-specialized PV_HainsworthFoote (buffer proph propf threshold waittime))
(define-specialized PV_JensenAndersen (buffer propsc prophfe prophfc propsf threshold waittime))
(define-specialized PV_LocalMax ())
(define-specialized PV_MagAbove ())
(define-specialized PV_MagBelow ())
(define-specialized PV_MagClip ())
(define-specialized PV_MagFreeze ())
(define-specialized PV_MagMul ())
(define-specialized PV_MagNoise ())
(define-specialized PV_MagShift ())
(define-specialized PV_MagSmear ())
(define-specialized PV_MagSquared ())
(define-specialized PV_Max ())
(define-specialized PV_Min ())
(define-specialized PV_Mul ())
(define-specialized PV_PhaseShift270 ())
(define-specialized PV_PhaseShift90 ())
(define-specialized PV_PhaseShift ())
(define-specialized PV_RandComb ())
(define-specialized PV_RandWipe ())
(define-specialized PV_RectComb2 ())
(define-specialized PV_RectComb ())

;; Local Variables:
;; truncate-lines:t
;; End:            
