;; make.scm - (c) rohan drape, 2005

(define (uspec-compile s)
  (let ((name (uspec-name/constructor s)))
    `(define-ugen ,name ,(symbol-++ name '-uspec))))

(load "/home/rohan/sw.cvs/sw-46/scheme/uspecs.scm")

(let ((p! (lambda (v) (display*! v (current-output-port))))
      (f  (rsc-file "scheme/ugen/procedures.scm")))
  (unlink*! f)
  (with-output-to-file! 
   f
   (lambda () 
     (p! ";; procedures.scm - (c) rohan drape, 2004-2005")
     (p! ";; THIS FILE IS AUTOMATICALLY GENERATED, DO NOT EDIT")
     (for-each! 
      p! 
      (map uspec-compile uspecs)))))
