;; harmonic tumbling (jmcc)

(let* ((f 80)
       (p 10)
       (t (xline kr (mce2 10 11) 0.1 60 0))
       (o (lambda (h)
	    (let* ((n (dust kr t))
		   (r (rand 0.25 0.5))
		   (e (decay2 (mul n 0.02) 0.005 r)))
	      (mul (fsin-osc ar (* f (+ h 1)) 0) e)))))
  (audition (out 0 (mix-fill p o))))
