;; shifting pulses (rd)

(let* ((wrp (lambda (i l r) (lin-lin i -1 1 l r)))
       (n1 (clone 2 (brown-noise kr)))
       (n2 (clone 2 (brown-noise kr)))
       (n3 (clone 2 (brown-noise kr)))
       (t (dust kr 0.75))
       (l (latch t t))
       (p (mul (pulse ar (wrp n1 2 (mce2 11 15)) 0.01) 0.1))
       (f (wrp n2 300 1800))
       (rq (wrp n3 0.01 2)))
  (audition (out 0 (mul l (rlpf p f rq)))))
