# Makefile - (c) rohan drape, 2003-2005

# Make a TAGS file for all scheme sources one level deep.  The emacs
# RSC mode uses this TAGS file to lookup documentation for procedures.

tags:	*/*.scm
	r.tags */*.scm
